name: Bazel build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-examples:
    name: Build & Test - Examples
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # - uses: cachix/install-nix-action@V27
      #   with:
      #     nix_path: nixpkgs=./nixpkgs.nix
      # - uses: ./.github/actions/configure_bazelrc
      #   with:
      #     buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
      - name: Build & Run
        run: |
          echo
          echo "::group::Running $(head -n1 README.md) without Nix"
          bazel build -s :hello
          bazel-bin/hello

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: failure()


  all_ci_tests:
    runs-on: ubuntu-latest
    needs:
      - test-examples
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@794a2d117251f22607f1aab937d3fd3eaaf9a2f5 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
