name: Changed

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  changed:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Changed files
        run: |
          set -xv
          git fetch origin ${{ github.base_ref || github.sha }}
          git diff --name-only ${GITHUB_BASE_REF:+origin/}${{ github.base_ref || github.sha }}..







