name: Changed

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  changed:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Changed files
        id: changed
        if: github.event_name == 'pull_request'
        run: |
          set -xv
          if [[ -n "$GITHUB_BASE_REF" ]]; then
             git fetch origin "$GITHUB_BASE_REF"
             git diff --name-only "origin/$GITHUB_BASE_REF"..
             echo "result=$( git diff --quiet "origin/$GITHUB_BASE_REF".. -- .github && echo no || echo yes )" >> "$GITHUB_OUTPUT"
          fi
      - name: Report
        if: ${{ steps.changed.outputs.result == 'yes' }}
        run: echo YES







