name: Check PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-examples:
    name: Build & Test - Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git show
          git log -3





