name: compile

on:
  push:

jobs:
  build:
    runs-on: macos-14

    steps:
      - run: echo $GITHUB_REF
      - uses: actions/checkout@v4
      - run: tar xvzf code_compile.tar.gz
      - run: brew install llvm@16
      - run: echo /usr/local/opt/llvm/bin/ >> "$GITHUB_PATH"
      - run: clang --version
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v4
      - run: ninja -f native/build.ninja
      - run: ./scalals-out

