name: compile

on:
  push:

jobs:
  build:
    runs-on: macos-14

    steps:
      - run: echo $GITHUB_REF
      - uses: actions/checkout@v4
      - run: tar xvzf code_compile.tar.gz
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.2
        with:
          version: "16.0.5"
      - run: clang --version
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v4
      - run: ninja -f native/build.ninja
      - run: ./scalals-out

