name: compile

on:
  push:

jobs:
  build:
    runs-on: macos-14

    steps:
      - run: echo $GITHUB_REF
      - uses: actions/checkout@v4
      - run: tar xvzf code_compile.tar.gz
      - run: brew install llvm@16
      - run: echo /opt/homebrew/opt/llvm@16/bin >> "$GITHUB_PATH"
      - run: clang --version
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v4
      - run: cp time_nano.c native/native-code-nativelib_native0.4_3-0.4.17-2/scala-native/time_nano.c
      - run: ninja -f build.ninja
      - run: ./scalals-out

