name: Test Release

on:
  release:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Runner
        run: |
          cat <<'EOF'
          ${{ toJSON(runner) }}
          EOF
      - name: Github
        run: |
          cat <<'EOF'
          ${{ toJSON(github) }}
          EOF
      - name: Job
        run: |
          cat <<'EOF'
          ${{ toJSON(job) }}
          EOF
      - name: Steps
        run: |
          cat <<'EOF'
          ${{ toJSON(steps) }}
          EOF
      - run: |
          echo https://jitpack.io/com/github/avdv/scalals/${{ github.ref_name }}/scalals-${{ github.ref_name }}.pom

