name: Whatever

on:
  push:
  workflow_dispatch:

jobs:
  whatever:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: a
        id: a
        uses: ./.github/actions/run-nix-shell
        with:
          pure: false
          run: |
            echo "output to: $GITHUB_OUTPUT"
            echo "foo_bar=what" >> "$GITHUB_OUTPUT"
            cat "$GITHUB_OUTPUT"

      - name: b
        id: b
        run: |
          echo '${{ toJson ( steps.a.outputs ) }}'
          echo '${{ toJson ( steps.a ) }}'
          echo '${{ toJson ( steps ) }}'
          echo "${{ steps.a.outputs.foo_bar }}"k
