name: Test Darwin

on:
  push:
  schedule:
    - cron: '0 16 * * 1' # every monday at 16:00

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        llvm: [11, 12, 13, 14, 15]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    name: "LLVM ${{matrix.llvm}} on ${{matrix.os}}"
    steps:
      - run: echo $GITHUB_REF
      - uses: actions/checkout@v3
      - name: "Install Nix ❄"
        uses: cachix/install-nix-action@v20
      - name: "Install Cachix ❄"
        uses: cachix/cachix-action@v12
        with:
          name: cbley
      - run: nix flake update
      - run: echo ${{ matrix.llvm }} > llvmVersion.nix
      - run: nix build --print-build-logs
