name: Ruby

on:
  push:
    branches: [ main ]
    tags: [ 'v[0-9]*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo $GITHUB_REF
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
