
name: Test Nix Shell

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.05-small

      - uses: actions/checkout@v4

      - run: echo hello

      - run: cowsay hello
        shell: nix-shell --argstr script {0} ci.nix --run ci.nix

