name: GHC Hadrian

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo $GITHUB_REF
      - run: curl -LO https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-src.tar.xz
      - run: tar xaf ghc-9.2.5-src.tar.xz
      - run: cabal update
      - run: |
          cd ghc-9.2.5
          ./boot
          ./configure
          hadrian/build -j binary-dist
      - name: Upload dist
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          name: 'ghc-9.2.5'
          tag_name: 'ghc-9.2.5'
          files: |
            _build/bindist/ghc-9.2.5-x86_64-unknown-linux.tar.xz
