name: Test Darwin

on:
  push:

jobs:
  test: 
    strategy:
      fail-fast: false
      matrix:
        llvm: [11, 12, 13, 14]
    runs-on: macos-latest

    name: "LLVM ${{matrix.llvm}}"
    steps:
      - run: echo $GITHUB_REF
      - uses: actions/checkout@v3
      - name: "Install Nix ❄"
        uses: cachix/install-nix-action@v18
      - name: "Install Cachix ❄"
        uses: cachix/cachix-action@v12
        with:
          name: cbley
      - run: echo ${{ matrix.llvm }} > llvmVersion.nix
      - run: nix build --print-build-logs


