name: Ruby

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo $GITHUB_REF
      - run: echo ${{ hashFiles('LICENSE') }}
