name: Ruby

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: "Install Nix ❄"
        uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: echo $GITHUB_REF
      - run: |
          nix-shell -I nixpkgs=https://nixos.org/channels/nixos-23.05 --command 'find -type f -print0 | strip-nondeterminism'
          nix-shell -I nixpkgs=https://nixos.org/channels/nixos-unstable --command 'find -type f -print0 | strip-nondeterminism'
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      #  with:
      #    limit-access-to-actor: true
