name: Ruby

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: "Install Nix ❄"
        uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: echo $GITHUB_REF
      - run: |
          nix-channel --add https://nixos.org/channels/nixos-23.05 nixpkgs
          nix-channel --update nixpkgs
          nix-shell --command 'find -type f -print0 | xargs -r0 strip-nondeterminism' || true
          nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
          nix-channel --update nixpkgs
          nix-shell --command 'find -type f -print0 | xargs -r0 strip-nondeterminism'
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      #  with:
      #    limit-access-to-actor: true
